version: "3"

services:
  server:
    image: golang:latest
    container_name: websocket_server
    tty: true
    volumes:
      - ./golang:/server
    working_dir: /server
    ports:
      - 8888:8888
    environment:
      - GOPATH=/server

  app:
    image: node:latest
    container_name: websocket_app
    tty: true
    volumes:
      - ./vue:/app
    working_dir: /app
    ports:
      - 80:8080
